name: Deploy Firebase Cloud Functions

on:
  push:
    branches:
      - main
    paths:
      - functions/**
      - ".github/workflows/deploy-functions.yml"
    tags-ignore:
      - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: cd functions && npm ci
      - name: Deploy to Firebase
        # https://github.com/w9jds/firebase-action/issues/233
        uses: w9jds/firebase-action@v13.7.2
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
