name: Web-Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "functions/**"
      - "docs/**"

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: production

    # https://github.com/FirebaseExtended/action-hosting-deploy/issues/321
    # permission for bot comment
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # temporary workaround for prevent Next.js "Checking validity of types" when build
      - name: Delete functions folder
        run: rm -rf functions/

      - name: Fetch files from private repo
        run: |
          mkdir -p shared src/renderer
          curl -H "Authorization: token ${{ secrets.PRIVATE_REPO_TOKEN }}" \
               -H "Accept: application/vnd.github.v3.raw" \
               https://api.github.com/repos/siriwatknp/scrapee/contents/shared/schema-production.ts \
               -o shared/schema-production.ts \
               https://api.github.com/repos/siriwatknp/scrapee/contents/src/renderer/types.d.ts \
               -o src/renderer/types.d.ts

      - name: Install & Build
        run: npm ci && npm run build
        env:
          NEXT_PUBLIC_FIREBASE_ENV: ${{ vars.NEXT_PUBLIC_FIREBASE_ENV }}
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
          NEXT_PUBLIC_LINE_LIFF_ID: ${{ secrets.NEXT_PUBLIC_LINE_LIFF_ID }}

      - name: Update firebase.json hosting site
        run: |
          jq '.hosting += {"site": "${{ secrets.FIREBASE_SITE_TARGET || secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"}' firebase.json > temp.json && mv temp.json firebase.json

      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"
          channelId: live
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
